// palletizing-application/src/app/components/main-page/main-page.component.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  EventEmitter,
  Output,
  ViewChild,
} from '@angular/core';
import { FormControl } from '@angular/forms';
import {
  PALLET_WIDTH_FACTOR,
  palletMapping,
} from 'src/app/constants/app.constant';
import {
  IObject,
  IObjectDimension,
  Orientation,
  PalletType,
  States,
} from 'src/app/models/app.model';
import { calculateAspectRatio } from 'src/app/utils/app.util';

@Component({
  selector: '[app-main-page]',
  templateUrl: './main-page.component.html',
  styleUrls: ['./main-page.component.scss'],
})
export class MainPageComponent implements AfterViewInit {
  @Output() gotoNextPageEvent = new EventEmitter<{
    state: States;
    objects: IObject[];
    pallet: PalletType;
    numberOfObjects: number;
    dimension: IObjectDimension;
  }>();
  palletPlanningControl = new FormControl<boolean>(true);
  objectLengthControl = new FormControl<number>(1);
  objectWidthControl = new FormControl<number>(1);
  numberOfObjectsControl = new FormControl<number>(1);
  palletType: PalletType = 'EURO 1';
  objectOrientation: 'HORIZONTAL' | 'VERTICAL' = 'HORIZONTAL';
  palletWidth = 0;
  palletHeight = 0;
  objectMaxHeight = 0;
  objectMaxWidth = 0;
  objectsInPallet: { orientation: Orientation }[] = [];
  selectedObject: { object: Orientation; index: number } | null = null;
  palletMappings = palletMapping;
  boundryDimensions: DOMRect | null = null;
  aspectRatio!: { aspectWidth: number; aspectHeight: number };

  @ViewChild('palletArea') palletArea!: ElementRef<HTMLDivElement>;
  @ViewChild('palletBox') palletBox!: ElementRef<HTMLDivElement>;

  ngAfterViewInit(): void {
    // timeout is simply to avoid template load warning
    setTimeout(() => {
      this.selectPalletType('EURO 1');
    }, 100);
  }

  /**
   * The savePalletSettings function updates the value of the palletPlanningControl to false.
   */
  savePalletSettings() {
    this.palletPlanningControl.patchValue(false);
  }

  /**
   * The `copyObject` function copies the selected object and adds it to the objects in the pallet.
   */
  copyObject() {
    if (this.selectedObject && this.isWithinBoundary()) {
      this.objectsInPallet.push({ orientation: this.selectedObject.object });
      // this.reAssignDragableEventListeners();
    }
  }

  addObject() {
    if (
      this.objectWidthControl.value &&
      this.objectLengthControl.value &&
      this.isWithinBoundary()
    ) {
      this.objectsInPallet.push({
        orientation: this.objectOrientation,
      });
      this.reAssignDragableEventListeners();
    }
  }

  reAssignDragableEventListeners() {
    setTimeout(() => {
      let items = document.querySelectorAll('.object');
      console.log(items);

      items.forEach((item) => {
        console.log(item);

        item.addEventListener('dragstart', this.handleDragStart);
        item.addEventListener('dragend', this.handleDragEnd);
      });
    }, 500);
  }

  handleDragStart(e: any) {
    // const boundry = this.palletBox.nativeElement.getBoundingClientRect();
    console.log(this.boundryDimensions, e);
  }

  handleDragEnd(e: any) {
    // console.log(this.palletBox.nativeElement.getBoundingClientRect(), e);
  }

  getPalletDimensionMapping(pallet: PalletType) {
    return palletMapping[pallet];
  }

  /**
   * The function sets the dimensions of a pallet based on a given pallet type and the width of a
   * container.
   */
  private setPalletDimension() {
    const pallet = this.getPalletDimensionMapping(this.palletType);
    this.aspectRatio = calculateAspectRatio(pallet.width, pallet.length);
    // setting pallet sixe - with to 80% of visible screen then height is
    // calculated based on aspect ratio to the width
    const palletContainerWidth = this.palletArea.nativeElement.offsetWidth;
    this.palletWidth = palletContainerWidth * PALLET_WIDTH_FACTOR;
    this.palletHeight =
      (this.palletWidth / this.aspectRatio.aspectWidth) *
      this.aspectRatio.aspectHeight;
    console.log(this.palletWidth, this.palletHeight);
  }

  /**
   * The function "selectPalletType" sets the pallet type, dimensions, and input range limits.
   * @param {PalletType} palletType - The `palletType` parameter is a variable of type `PalletType`. It
   * is used to specify the type of pallet that will be selected.
   */
  selectPalletType(palletType: PalletType) {
    this.palletType = palletType;
    this.setPalletDimension();
    this.setInputRangeLimits();
  }

  /**
   * The function sets the input range limits for the pallet width and length controls, and updates the
   * maximum height and width of the object based on the pallet dimensions.
   */
  private setInputRangeLimits() {
    this.objectWidthControl.patchValue(1);
    this.objectLengthControl.patchValue(1);
    this.objectMaxHeight = this.palletHeight;
    this.objectMaxWidth = this.palletWidth;
  }

  /**
   * The function "selectObjectForModification" selects an object and its index for modification.
   * @param {IObject} object - The "object" parameter is of type IObject, which means it represents an
   * object with specific properties and methods defined in the IObject interface.
   * @param {number} index - The index parameter is a number that represents the position of the object
   * in a collection or array.
   */
  selectObjectForModification(object: Orientation, index: number) {
    this.selectedObject = { object, index };
  }

  /**
   * The `removeObject` function removes the selected object from the `objectsInPallet` array.
   */
  removeObject() {
    if (this.selectedObject) {
      this.objectsInPallet.splice(this.selectedObject.index, 1);
      this.selectedObject = null;
    }
  }

  /**
   * The savePallet function calculates object positions and emits an event with the objects, pallet
   * type, number of objects, and pallet dimensions if all required values are provided.
   */
  savePallet() {
    // this.calculateObjectPositions();
    if (
      this.numberOfObjectsControl.value &&
      this.objectLengthControl.value &&
      this.objectWidthControl.value
    ) {
      this.gotoNextPageEvent.emit({
        state: 'FINISH',
        objects: this.getObjectsInPallet(),
        pallet: this.palletType,
        numberOfObjects: this.numberOfObjectsControl.value,
        dimension: this.getPalletDimensionMapping(this.palletType),
      });
    }
  }

  /**
   * The function calculates the positions of objects on a pallet based on their orientation and the
   * dimensions of the pallet.
   */
  getObjectsInPallet() {
    const palletLength = this.objectLengthControl.value;
    const palletWidth = this.objectWidthControl.value;
    const objects: IObject[] = [];

    this.objectsInPallet.map((object, index) => {
      const objectPositions = document
        .getElementById('object-' + index)
        ?.getBoundingClientRect();

      if (objectPositions && palletLength && palletWidth) {
        const xDiff = objectPositions.x - this.boundryDimensions!.x;
        const yDiff = objectPositions.y - this.boundryDimensions!.y;
        console.log(xDiff, yDiff, objectPositions, this.boundryDimensions);

        const aspectWidth = this.aspectRatio.aspectWidth;
        const aspectHeight = this.aspectRatio.aspectHeight;
        // const pallet = this.getPalletDimensionMapping(this.palletType);
        console.log(aspectWidth, aspectHeight);

        const x =
          object.orientation === 'VERTICAL'
            ? xDiff + (palletLength / 2) * aspectHeight
            : xDiff + (palletWidth / 2) * aspectWidth;
        // object.orientation === 'VERTICAL'
        //   ? ((xDiff + palletLength / 2) / palletLength) * pallet.length
        //   : ((xDiff + palletWidth / 2) / palletWidth) * pallet.width;

        const y =
          object.orientation === 'VERTICAL'
            ? yDiff + (palletWidth / 2) * aspectWidth
            : yDiff + (palletLength / 2) * aspectHeight;
        // object.orientation === 'VERTICAL'
        //   ? ((yDiff + palletWidth / 2) / palletWidth) * pallet.width
        //   : ((yDiff + palletLength / 2) / palletLength) * pallet.length;

        objects.push({
          x,
          y,
          orientation: object.orientation,
        });
      }
    });
    return objects;
  }

  /**
   * The function `isWithinBoundary()` checks if the last object in a pallet exceeds the boundaries
   * of the pallet and returns true if it does not, or false if it does.
   * @returns a boolean value. If the condition in the if statement is true, it will return false.
   * Otherwise, it will return true.
   */

  private isWithinBoundary() {
    if (
      this.objectsInPallet.length > 0 &&
      this.objectLengthControl.value &&
      this.objectWidthControl.value
    ) {
      const lastObjectDimensions = document
        .getElementById('object-' + (this.objectsInPallet.length - 1))
        ?.getBoundingClientRect();
      this.boundryDimensions =
        this.palletBox.nativeElement.getBoundingClientRect();

      if (lastObjectDimensions) {
        const objectRight = lastObjectDimensions.right;
        const objectBottom = lastObjectDimensions.bottom;

        const isRightSideOverflow =
          (this.objectOrientation === 'HORIZONTAL' &&
            objectRight + this.objectWidthControl.value >
              this.boundryDimensions.right) ||
          (this.objectOrientation === 'VERTICAL' &&
            objectRight + this.objectLengthControl.value >
              this.boundryDimensions.right);

        const isBottomSideOverflow =
          objectBottom +
            (this.objectOrientation === 'HORIZONTAL'
              ? this.objectLengthControl.value
              : this.objectWidthControl.value) >
          (this.objectOrientation === 'HORIZONTAL'
            ? this.boundryDimensions.bottom
            : this.boundryDimensions.bottom);

        if (isRightSideOverflow && isBottomSideOverflow) {
          alert('Pallet is full');
          return false;
        }
      }
    }
    return true;
  }
}

<!-- left side -->
<div class="col-4 border-thin p-0 py-3">
  <div class="head text-right border-bottom-thin px-2">
    <span class="label">Pallet Planning </span>
    <label class="switch">
      <input type="checkbox" [formControl]="palletPlanningControl" />
      <span class="slider round"></span>
    </label>
  </div>
  <div class="content p-4">
    <div [ngClass]="{ overlay: !palletPlanningControl.value }"></div>
    <!-- pallet type selection -->
    <div class="row">
      <div class="col-12">
        <p>Pallet Info</p>
      </div>
      <div class="col-6" *ngFor="let pallet of palletMappings | keyvalue">
        <app-pallet-type
          [sellectedPallet]="palletType"
          [palletType]="pallet.key"
          (palletTypeChangeEvent)="selectPalletType($event)"
        ></app-pallet-type>
      </div>
    </div>

    <!-- pallet properties -->
    <div class="row mt-5">
      <div class="col-12">
        <p>Object Dimension</p>
      </div>
      <div class="col-8 mt-4">
        <div
          app-range-inputs
          inputId="length"
          label="Length mm"
          [control]="objectLengthControl"
          [max]="objectMaxHeight"
          [step]="1"
        ></div>
      </div>
      <div class="col-4 mt-4">
        <input
          type="number"
          class="form-control mt-3"
          [ngModel]="objectLengthControl.value"
          [disabled]="true"
        />
      </div>
      <!-- object dimension -->
      <div class="col-8 mt-5">
        <div
          app-range-inputs
          inputId="width"
          label="Width mm"
          [control]="objectWidthControl"
          [max]="objectMaxWidth"
          [step]="1"
        ></div>
      </div>
      <div class="col-4 mt-5">
        <input
          type="number"
          class="form-control mt-3"
          [ngModel]="objectWidthControl.value"
          [disabled]="true"
        />
      </div>
      <!-- number of objects -->
      <div class="col-8 mt-5">
        <label for="number-of-objects" class="pt-1">Number of Objects </label>
      </div>
      <div class="col-4 mt-5">
        <input
          type="number"
          class="form-control"
          [formControl]="numberOfObjectsControl"
        />
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12 text-right">
      <button
        type="button"
        class="btn btn-outline-dark m-3"
        (click)="savePalletSettings()"
      >
        Save
      </button>
    </div>
  </div>
</div>
<!-- right side -->
<div class="col-8 border-thin p-0 py-3">
  <div class="head border-bottom-thin px-2">
    <h5 class="m-0">{{ palletType }}</h5>
    <p>
      {{ getPalletDimensionMapping(palletType).length }} X
      {{ getPalletDimensionMapping(palletType).width }} (L X W)
    </p>
  </div>
  <div class="content text-center" #palletArea>
    <div [ngClass]="{ overlay: palletPlanningControl.value }"></div>
    <div class="row mx-0">
      <div class="col my-3 object-buttons">
        <img
          src="../assets/images/pallet-horizontal.png"
          alt=""
          class="object-button1"
          [ngClass]="{ selected: objectOrientation === 'HORIZONTAL' }"
          (click)="objectOrientation = 'HORIZONTAL'"
        />
        <img
          src="../assets/images/pallet-vertical.png"
          alt=""
          class="object-button2"
          [ngClass]="{ selected: objectOrientation === 'VERTICAL' }"
          (click)="objectOrientation = 'VERTICAL'"
        />
        <button
          type="button"
          class="btn btn-outline-dark add-object-button"
          (click)="addObject()"
        >
          <i class="fa-solid fa-plus"></i>
        </button>
      </div>
    </div>
    <div>
      <div
        #palletBox
        class="main-pallet-box m-auto"
        [style.width.px]="palletWidth"
        [style.height.px]="palletHeight"
      >
        <div
          *ngFor="let object of objectsInPallet; let i = index"
          class="object"
          [id]="'object-' + i"
          draggable="true"
          [style.width.px]="
            object.orientation === 'HORIZONTAL'
              ? objectWidthControl.value
              : objectLengthControl.value
          "
          [style.height.px]="
            object.orientation === 'HORIZONTAL'
              ? objectLengthControl.value
              : objectWidthControl.value
          "
          (click)="selectObjectForModification(object.orientation, i)"
          [ngClass]="selectedObject?.index === i ? 'selected' : ''"
        >
          {{ i }}
        </div>
      </div>
    </div>
  </div>

  <div class="col-12 mt-3 d-flex justify-content-between">
    <!-- 2 buttons to the left, one to the right -->
    <div class="text-left">
      <button
        type="button"
        class="btn btn-danger ml-2"
        (click)="removeObject()"
        *ngIf="selectedObject"
      >
        <i class="fa-regular fa-trash-can"></i>
      </button>
      <button
        type="button"
        class="btn btn-secondary ml-2"
        (click)="copyObject()"
        *ngIf="selectedObject"
      >
        <i class="fa-regular fa-copy"></i>
      </button>
    </div>
    <div class="text-right">
      <button
        type="button"
        class="btn btn-outline-dark ml-2"
        (click)="savePallet()"
        [disabled]="objectsInPallet.length !== numberOfObjectsControl.value"
      >
        save
      </button>
    </div>
  </div>
</div>

// palletizing-app-vue/src/components/MainPage.vue
<template>
  <div class="row">
    <!-- left side -->
    <div class="col-4 border-thin p-0 py-3">
      <div class="head text-right border-bottom-thin px-2">
        <span class="label">Pallet Planning </span>
        <label class="switch">
          <input type="checkbox" v-model="palletPlanning" />
          <span class="slider round"></span>
        </label>
      </div>
      <div class="content p-4">
        <div :class="{ overlay: !palletPlanning }"></div>
        <!-- pallet type selection -->
        <div class="row">
          <div class="col-12">
            <p>Pallet Info</p>
          </div>
          <div
            class="col-6"
            v-for="(value, key) in palletMappings"
            v-bind:key="value"
          >
            <PalletType
              :sellectedPallet="palletType"
              :palletType="key"
              @selectPallet="selectPalletType"
            />
          </div>
        </div>

        <div class="row mt-5">
          <div class="col-12">
            <p>Object Dimension</p>
          </div>
          <div class="col-8 mt-4">
            <!-- <div
              app-range-inputs
              inputId="length"
              label="Length mm"
              [control]="objectLengthControl"
              [max]="objectMaxHeight"
              [step]="1"
            ></div> -->
            <div class="form-group">
              <label for="length">Length mm</label>
              <input
                type="range"
                class="form-control-range"
                id="length"
                v-model="objectLengthControl"
                min="1"
                step="1"
                :max="objectMaxHeight"
              />
            </div>
          </div>
          <div class="col-4 mt-4">
            <input
              type="number"
              class="form-control mt-3"
              v-model="objectLengthControl"
            />
          </div>
          <div class="col-8 mt-5">
            <!-- <div
              app-range-inputs
              inputId="width"
              label="Width mm"
              [control]="objectWidthControl"
              [max]="objectMaxWidth"
              [step]="1"
            ></div> -->
            <div class="form-group">
              <label for="width">Width mm</label>
              <input
                type="range"
                class="form-control-range"
                id="width"
                v-model="objectWidthControl"
                min="1"
                step="1"
                :max="objectMaxWidth"
              />
            </div>
          </div>
          <div class="col-4 mt-5">
            <input
              type="number"
              class="form-control mt-3"
              v-model="objectWidthControl"
            />
          </div>
          <div class="col-8 mt-5">
            <label for="number-of-objects" class="pt-1"
              >Number of Objects
            </label>
          </div>
          <div class="col-4 mt-5">
            <input
              type="number"
              class="form-control"
              v-model="numberOfObjectsControl"
            />
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-12 text-right">
          <button
            type="button"
            class="btn btn-outline-dark m-3"
            @click="savePalletSettings()"
          >
            Save
          </button>
        </div>
      </div>
    </div>
    <!-- right side -->
    <div class="col-8 border-thin p-0 py-3">
      <div class="head border-bottom-thin px-2">
        <h5 class="m-0">{{ palletType }}</h5>
        <p>
          {{ getPalletDimensionMapping(palletType).length }} X
          {{ getPalletDimensionMapping(palletType).width }} (L X W)
        </p>
      </div>
      <div class="content text-center" id="palletArea">
        <div :class="{ overlay: palletPlanning }"></div>
        <div class="row mx-0">
          <div class="col my-3 object-buttons">
            <img
              src="../assets/images/pallet-horizontal.png"
              alt=""
              class="object-button1"
              :class="{ selected: objectOrientation === 'HORIZONTAL' }"
              @click="objectOrientation = 'HORIZONTAL'"
            />
            <img
              src="../assets/images/pallet-vertical.png"
              alt=""
              class="object-button2"
              :class="{ selected: objectOrientation === 'VERTICAL' }"
              @click="objectOrientation = 'VERTICAL'"
            />
            <button
              type="button"
              class="btn btn-outline-dark add-object-button"
              @click="addObject()"
            >
              <i class="fa-solid fa-plus"></i>
            </button>
          </div>
        </div>
        <div>
          <div
            id="palletBox"
            class="main-pallet-box m-auto"
            :style="{ width: palletWidth + 'px', height: palletHeight + 'px' }"
          >
            <div
              v-for="(object, index) in objectsInPallet"
              v-bind:key="index"
              class="object"
              :id="'object-' + index"
              draggable="true"
              :style="{
                width:
                  object.orientation === 'HORIZONTAL'
                    ? objectWidthControl + 'px'
                    : objectLengthControl + 'px',
                height:
                  object.orientation === 'HORIZONTAL'
                    ? objectLengthControl + 'px'
                    : objectWidthControl + 'px',
              }"
              @click="selectObjectForModification(object.orientation, index)"
              :class="{ selected: selectedObject?.index === index }"
            >
              {{ index }}
            </div>
          </div>
        </div>
      </div>

      <div class="col-12 mt-3 d-flex justify-content-between">
        <div class="text-left">
          <button
            type="button"
            class="btn btn-danger ml-2"
            @click="removeObject()"
            v-if="selectedObject"
          >
            <i class="fa-regular fa-trash-can"></i>
          </button>
          <button
            type="button"
            class="btn btn-secondary ml-2"
            @click="copyObject()"
            v-if="selectedObject"
          >
            <i class="fa-regular fa-copy"></i>
          </button>
        </div>
        <div class="text-right">
          <button
            type="button"
            class="btn btn-outline-dark ml-2"
            @click="savePallet()"
            :disabled="objectsInPallet.length !== numberOfObjectsControl"
          >
            save
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import PalletType from "./PalletType.vue";
export default {
  name: "MainPage",
  components: {
    PalletType,
  },

  data() {
    return {
      palletPlanning: true,
      objectLengthControl: 1,
      objectWidthControl: 1,
      numberOfObjectsControl: 1,
      palletType: "EURO 1",
      objectOrientation: "HORIZONTAL",
      palletWidth: 0,
      palletHeight: 0,
      objectMaxHeight: 0,
      objectMaxWidth: 0,
      objectsInPallet: [],
      selectedObject: null,
      palletMappings: {
        "EURO 1": {
          length: 1200,
          width: 800,
        },
        "EURO 2": {
          length: 1000,
          width: 1200,
        },
        "EURO 3": {
          length: 1200,
          width: 1000,
        },
        "EURO 4": {
          length: 600,
          width: 800,
        },
      },
      boundryDimensions: null,
      aspectRatio: undefined,
    };
  },
  props: {},
  methods: {
    goToNextPage() {
      this.$emit({ state: "FINISH" });
    },

    getPalletDimensionMapping(pallet) {
      return this.palletMappings[pallet];
    },

    selectPalletType(palletType) {
      this.palletType = palletType;
      this.setPalletDimension();
      this.setInputRangeLimits();
    },
    addObject() {
      if (
        this.objectWidthControl &&
        this.objectLengthControl &&
        this.isWithinBoundary()
      ) {
        this.objectsInPallet.push({
          orientation: this.objectOrientation,
        });
      }
    },
    isWithinBoundary() {
      if (
        this.objectsInPallet.length > 0 &&
        this.objectLengthControl &&
        this.objectWidthControl
      ) {
        const lastObjectDimensions = document
          .getElementById("object-" + (this.objectsInPallet.length - 1))
          ?.getBoundingClientRect();
        this.boundryDimensions = document
          .getElementById("palletBox")
          .getBoundingClientRect();

        if (lastObjectDimensions) {
          const objectRight = lastObjectDimensions.right;
          const objectBottom = lastObjectDimensions.bottom;

          const isRightSideOverflow =
            (this.objectOrientation === "HORIZONTAL" &&
              objectRight + this.objectWidthControl >
                this.boundryDimensions.right) ||
            (this.objectOrientation === "VERTICAL" &&
              objectRight + this.objectLengthControl >
                this.boundryDimensions.right);

          const isBottomSideOverflow =
            objectBottom +
              (this.objectOrientation === "HORIZONTAL"
                ? this.objectLengthControl
                : this.objectWidthControl) >
            (this.objectOrientation === "HORIZONTAL"
              ? this.boundryDimensions.bottom
              : this.boundryDimensions.bottom);

          if (isRightSideOverflow && isBottomSideOverflow) {
            alert("Pallet is full");
            return false;
          }
        }
      }
      return true;
    },
    selectObjectForModification(object, index) {
      this.selectedObject = { object, index };
    },
    removeObject() {
      if (this.selectedObject) {
        this.objectsInPallet.splice(this.selectedObject.index, 1);
        this.selectedObject = null;
      }
    },
    copyObject() {
      if (this.selectedObject && this.isWithinBoundary()) {
        this.objectsInPallet.push({ orientation: this.selectedObject.object });
      }
    },
    setPalletDimension() {
      const pallet = this.getPalletDimensionMapping(this.palletType);
      this.aspectRatio = this.calculateAspectRatio(pallet.width, pallet.length);
      // setting pallet sixe - with to 80% of visible screen then height is
      // calculated based on aspect ratio to the width
      const palletContainerWidth =
        document.getElementById("palletArea").offsetWidth;
      this.palletWidth = palletContainerWidth * 0.8;
      this.palletHeight =
        (this.palletWidth / this.aspectRatio.aspectWidth) *
        this.aspectRatio.aspectHeight;
    },

    setInputRangeLimits() {
      this.objectWidthControl = 1;
      this.objectLengthControl = 1;
      this.objectMaxHeight = this.palletHeight;
      this.objectMaxWidth = this.palletWidth;
    },
    savePallet() {
      if (
        this.numberOfObjectsControl &&
        this.objectLengthControl &&
        this.objectWidthControl
      ) {
        this.$emit("goToNextPage", {
          state: "FINISH",
          objects: this.getObjectsInPallet(),
          pallet: this.palletType,
          numberOfObjects: this.numberOfObjectsControl,
          dimension: this.getPalletDimensionMapping(this.palletType),
        });
      }
    },
    getObjectsInPallet() {
      const palletLength = this.objectLengthControl;
      const palletWidth = this.objectWidthControl;
      const objects = [];

      this.objectsInPallet.map((object, index) => {
        const objectPositions = document
          .getElementById("object-" + index)
          ?.getBoundingClientRect();

        if (objectPositions && palletLength && palletWidth) {
          const xDiff = objectPositions.x - this.boundryDimensions.x;
          const yDiff = objectPositions.y - this.boundryDimensions.y;

          const aspectWidth = this.aspectRatio.aspectWidth;
          const aspectHeight = this.aspectRatio.aspectHeight;

          const x =
            object.orientation === "VERTICAL"
              ? xDiff + (palletLength / 2) * aspectHeight
              : xDiff + (palletWidth / 2) * aspectWidth;
          // object.orientation === 'VERTICAL'
          //   ? ((xDiff + palletLength / 2) / palletLength) * pallet.length
          //   : ((xDiff + palletWidth / 2) / palletWidth) * pallet.width;

          const y =
            object.orientation === "VERTICAL"
              ? yDiff + (palletWidth / 2) * aspectWidth
              : yDiff + (palletLength / 2) * aspectHeight;
          // object.orientation === 'VERTICAL'
          //   ? ((yDiff + palletWidth / 2) / palletWidth) * pallet.width
          //   : ((yDiff + palletLength / 2) / palletLength) * pallet.length;

          objects.push({
            x,
            y,
            orientation: object.orientation,
          });
        }
      });
      return objects;
    },
    savePalletSettings() {
      this.palletPlanning = false;
    },
    // utility methods
    calculateAspectRatio(width, height) {
      const bigger = width > height ? width : height;
      const smaller = width < height ? width : height;

      const divisor = this.gcd(bigger, smaller);
      const aspectBigger = bigger / divisor;
      const aspectSmaller = smaller / divisor;

      if (width > height) {
        return { aspectWidth: aspectBigger, aspectHeight: aspectSmaller };
      } else {
        return { aspectWidth: aspectSmaller, aspectHeight: aspectBigger };
      }
    },
    gcd(a, b) {
      if (b === 0) {
        return a;
      }
      return this.gcd(b, a % b);
    },
  },

  mounted() {
    this.selectPalletType("EURO 1");
  },
};
</script>
<style></style>
