// palletizing-app-vue/src/components/PalletType.vue
<template>
  <div
    class="pallet"
    @click="selectPallet()"
    :class="{ selected: sellectedPallet === palletType }"
  >
    {{ palletType }}
  </div>
</template>

<script>
export default {
  name: "PalletType",
  props: {
    palletType: String,
    sellectedPallet: String,
  },
  methods: {
    selectPallet() {
      this.$emit("selectPallet", this.palletType);
    },
  },
};
</script>
<style scoped></style>

// palletizing-application/src/app/components/pallet-type/pallet-type.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { PalletType } from 'src/app/models/app.model';

@Component({
  selector: 'app-pallet-type',
  templateUrl: './pallet-type.component.html',
})
export class PalletTypeComponent {
  @Input() palletType!: string;
  @Input() sellectedPallet!: PalletType;
  @Output() palletTypeChangeEvent = new EventEmitter<PalletType>();

  selectPallet() {
    this.palletTypeChangeEvent.emit(this.palletType as PalletType);
  }
}

<div
  class="pallet"
  (click)="selectPallet()"
  [ngClass]="{ selected: sellectedPallet === palletType }"
>
  {{ palletType }}
</div>
