// palletizing-app-vue/src/App.vue
<template>
  <section class="container mt-4">
    <div class="row">
      <div class="col-12">
        <h3 class="text-center">Palletizing Application</h3>
      </div>
    </div>
  </section>
  <section class="container mt-4">
    <!-- 1st page -->
    <!-- <div > -->
    <!-- {{ state }} -->
    <!-- </div> -->

    <InitailPage @goToNextPage="goToNextPage" v-if="state === 'INITIAL'" />
    <MainPage @goToNextPage="goToNextPage" v-if="state === 'MAIN'" />
    <FinalPage
      @goToNextPage="goToNextPage"
      v-bind:payload="payload"
      v-if="state === 'FINISH'"
    />
  </section>
</template>

<script>
import InitailPage from "./components/InitailPage.vue";
import MainPage from "./components/MainPage.vue";
import FinalPage from "./components/FinalPage.vue";

export default {
  name: "App",
  data() {
    return {
      state: "INITIAL",
      payload: undefined,
    };
  },
  components: {
    InitailPage,
    MainPage,
    FinalPage,
  },
  methods: {
    goToNextPage(event) {
      this.state = event.state;
      if (event.objects) {
        this.payload = {
          numberOfObjects: event.numberOfObjects,
          objectDimension: event.dimension,
          objects: event.objects,
          pallet: event.pallet,
        };
      }
    },
  },
};
</script>

<style></style>

// palletizing-application/src/app/app.component.ts
import { Component } from '@angular/core';
import {
  IObject,
  IObjectDimension,
  IPalletPayload,
  PalletType,
  States,
} from './models/app.model';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  state: States = 'INITIAL';
  payload!: IPalletPayload;

  /**
   * The function "goToNextPage" updates the state and sets the payload based on the provided event
   * object.
   * @param event - The event parameter is an object that contains the following properties:
   */
  goToNextPage(event: {
    state: States;
    objects?: IObject[];
    pallet?: PalletType;
    numberOfObjects?: number;
    dimension?: IObjectDimension;
  }) {
    this.state = event.state;
    if (event.objects) {
      this.payload = {
        numberOfObjects: event.numberOfObjects,
        objectDimension: event.dimension,
        objects: event.objects,
        pallet: event.pallet,
      };
    }
  }
}

<section class="container mt-4">
  <div class="row">
    <div class="col-12">
      <h3 class="text-center">Palletizing Application</h3>
    </div>
  </div>
</section>
<section class="container mt-4">
  <!-- 1st page -->
  <div
    class="row"
    *ngIf="state === 'INITIAL'"
    app-initial-page
    (gotoNextPageEvent)="goToNextPage({ state: 'MAIN' })"
  ></div>

  <!-- 2nd page -->
  <div
    app-main-page
    class="row"
    *ngIf="state === 'MAIN'"
    (gotoNextPageEvent)="goToNextPage($event)"
  ></div>

  <!-- 3rd or finish page -->

  <div
    app-finish-page
    class="row"
    *ngIf="state === 'FINISH'"
    [payload]="payload"
    (gotoNextPageEvent)="goToNextPage({ state: 'INITIAL' })"
  ></div>
</section>
